USE [MoneyTransferCore]
GO
DECLARE @business_id BIGINT;
SELECT 
 TOP 1 @business_id = [business_id]
FROM 
 [MoneyTransferCore].[dbo].[business_equipment] 
WHERE 
 equipment_status_id <> 3 
 AND equipment_type_id = 10 
ORDER BY 
    last_updated DESC

INSERT INTO [dbo].[business_equipment]
            ([date_created]
            ,[last_updated]
            ,[updated_by_id]
            ,[created_by_id]
            ,[created_by_device_id]
            ,[updated_by_device_id]
            ,[equipment_status_id]
            ,[equipment_type_id]
            ,[equipment_name]
            ,[equipment_desc]
            ,[manufacturer]
            ,[serial_number]
            ,[part_model_number]
            ,[our_purchase_price]
            ,[our_purchase_date]
            ,[equipment_location_id]
            ,[mac_address]
            ,[business_id]
            ,[business_deposit]
            ,[business_cost]
            ,[transaction_date]
            ,[transaction_type_id]
            ,[return_date]
            ,[replacement_cost]
            ,[employee_id]
            ,[installation_date]
            ,[notes]
            ,[aml_block]
            ,[aml_watch]
            ,[application_id]
            ,[unique_id]
            ,[wildcard])
        SELECT 
         TOP 1
         [date_created]
            ,[last_updated]
            ,[updated_by_id]
            ,[created_by_id]
            ,[created_by_device_id]
            ,[updated_by_device_id]
            ,[equipment_status_id]
            ,[equipment_type_id]
            ,[equipment_name]
            ,[equipment_desc]
            ,[manufacturer]
            ,[serial_number]
            ,[part_model_number]
            ,[our_purchase_price]
            ,[our_purchase_date]
            ,[equipment_location_id]
            ,'C8:1F:66:0F:5E:C7' -- like 'F8:BC:12:96:4B:88'
            ,[business_id]
            ,[business_deposit]
            ,[business_cost]
            ,[transaction_date]
            ,[transaction_type_id]
            ,[return_date]
            ,[replacement_cost]
            ,[employee_id]
            ,[installation_date]
            ,[notes]
            ,[aml_block]
            ,[aml_watch]
            ,[application_id]
            ,[unique_id]
            ,[wildcard]
        FROM 
            [MoneyTransferCore].[dbo].[business_equipment] 
        WHERE 
            equipment_status_id <> 3 
            AND equipment_type_id = 10 
        ORDER BY last_updated DESC

INSERT INTO [dbo].[employee]
            ([employee_type_id]
            ,[business_id]
            ,[manager_id]
            ,[employee_status_code]
            ,[date_created]
            ,[last_updated]
            ,[updated_by_id]
            ,[created_by_id]
            ,[created_by_device_id]
            ,[updated_by_device_id]
            ,[first_name]
            ,[middle_name]
            ,[last_name]
            ,[address1]
            ,[address2]
            ,[city]
            ,[state_id]
            ,[zipcode]
            ,[country_id]
            ,[email_address]
            ,[nick_name]
            ,[ssn]
            ,[username]
            ,[password]
            ,[security_question_id]
            ,[security_answer]
            ,[home_phone_number]
            ,[cell_phone_number]
            ,[work_phone_number]
            ,[work_phone_number_extension]
            ,[ofac_status_code]
            ,[ofac_false_positive_reason_id]
            ,[aml_block]
            ,[aml_watch]
            ,[is_pos_admin]
            ,[can_login]
            ,[date_of_birth]
            ,[id_type_id]
            ,[id_number]
            ,[nationality_country_id]
            ,[id_state_id]
            ,[id_expiration_date]
            ,[city_id]
            ,[password_force_reset]
            ,[password_is_temporary]
            ,[super_user]
            ,[shadow_user]
            ,[floating])
        SELECT  
            TOP 1
            [employee_type_id]
            ,[business_id]
            ,[manager_id]
            ,[employee_status_code]
            ,[date_created]
            ,[last_updated]
            ,[updated_by_id]
            ,[created_by_id]
            ,[created_by_device_id]
            ,[updated_by_device_id]
            ,[first_name]
            ,[middle_name]
            ,[last_name]
            ,[address1]
            ,[address2]
            ,[city]
            ,[state_id]
            ,[zipcode]
            ,[country_id]
            ,[email_address]
            ,[nick_name]
            ,[ssn]
            ,'augmentum\jimmy.li' -- like 'augmentum\immonen.xu'
            ,[password]
            ,[security_question_id]
            ,[security_answer]
            ,[home_phone_number]
            ,[cell_phone_number]
            ,[work_phone_number]
            ,[work_phone_number_extension]
            ,[ofac_status_code]
            ,[ofac_false_positive_reason_id]
            ,[aml_block]
            ,[aml_watch]
            ,[is_pos_admin]
            ,[can_login]
            ,[date_of_birth]
            ,[id_type_id]
            ,[id_number]
            ,[nationality_country_id]
            ,[id_state_id]
            ,[id_expiration_date]
            ,[city_id]
            ,[password_force_reset]
            ,[password_is_temporary]
            ,[super_user]
            ,[shadow_user]
            ,[floating]
        FROM 
            MoneyTransferCore.[dbo].[employee] 
        WHERE 
            business_id = @business_id 
            AND employee_status_code <> 'D'
        ORDER BY 
            last_updated DESC